const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');const overlay=document.getElementById('startOverlay'),start=document.getElementById('startBtn'),jumpBtn=document.getElementById('jumpBtn'),stageText=document.getElementById('stageLabel'),status=document.getElementById('statusLabel'),msg=document.getElementById('messageBox');
const ground=430,total=100,gravity=1700,jumpPower=700;let stage=1,running=false,last=0,cam=0,player,obstacles=[],overheads=[],messageTimer=0;
const themes=n=>n<=10?'شارع عربي':n<=20?'حي عربي':n<=30?'سوق شعبي':n<=40?'صحراء':n<=50?'جبال':n<=60?'مدينة':n<=80?'طريق سريع':'منطقة متقدمة';
function say(t,s=.8){msg.textContent=t;msg.classList.add('visible');messageTimer=s}function makeStage(){obstacles=[];overheads=[];let x=300;for(let i=0;i<Math.min(4+Math.floor(stage/12),12);i++){x+=180+Math.random()*100;let w=32+Math.random()*24,h=40+Math.random()*45;obstacles.push({x,y:ground-h,w,h});if(stage>3&&i%3===1)overheads.push({x:x-8,y:65,w:w+16,h:ground-h-75})}status.textContent=themes(stage);stageText.textContent=`${stage} / ${total}`}
function reset(){player={x:110,y:ground-70,w:48,h:70,vy:0,jumps:2,run:0};cam=0;makeStage()}
function begin(){stage=1;running=true;overlay.classList.remove('visible');reset();say('هذا عمر! ابدأ بالجري',1)}
function die(){if(!running)return;running=false;say('اصطدمت! إعادة المحاولة',1);setTimeout(()=>{reset();running=true},850)}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function triggerJump(){if(!running)return;if(player.jumps>0){player.vy=-jumpPower;player.jumps--;say(player.jumps?'قفزة أولى':'دبل نط',.35)}}window.triggerJump=triggerJump;
function update(dt){let right=keys.right?1:0,left=keys.left?1:0;player.x+=(right-left)*320*dt;player.run+=dt*12;player.vy+=gravity*dt;player.y+=player.vy*dt;if(player.y+player.h>=ground){player.y=ground-player.h;player.vy=0;player.jumps=2}player.x=Math.max(50,Math.min(player.x,stage*22+1750));cam=Math.max(0,player.x-380);if(obstacles.some(o=>hit(player,o))||overheads.some(o=>hit(player,o)))die();if(player.x>stage*22+1630){if(stage<total){stage++;reset();say(`المرحلة ${stage}`,1)}else{running=false;overlay.classList.add('visible');overlay.querySelector('h1').textContent='فزت يا عمر!';overlay.querySelector('p').textContent='أكملت 100 مرحلة.'}}}
const keys={right:false,left:false};window.addEventListener('keydown',e=>{if(e.code==='ArrowRight'||e.code==='KeyD')keys.right=true;if(e.code==='ArrowLeft'||e.code==='KeyA')keys.left=true;if((e.code==='Space'||e.code==='ArrowUp')&&!e.repeat){e.preventDefault();triggerJump()}});window.addEventListener('keyup',e=>{if(e.code==='ArrowRight'||e.code==='KeyD')keys.right=false;if(e.code==='ArrowLeft'||e.code==='KeyA')keys.left=false});start.onclick=begin;
function background(){let g=ctx.createLinearGradient(0,0,0,500);g.addColorStop(0,'#87c5ff');g.addColorStop(1,'#f5fbff');ctx.fillStyle=g;ctx.fillRect(0,0,1100,500);ctx.fillStyle='#ffd84d';ctx.beginPath();ctx.arc(900,85,40,0,7);ctx.fill();for(let i=0;i<18;i++){ctx.fillStyle='rgba(70,90,120,.3)';ctx.fillRect((i*120-cam*.2)%1250,220-(i%4)*20,80,140+(i%4)*20)}ctx.fillStyle='#3b4650';ctx.fillRect(0,440,1100,60);ctx.fillStyle='#fff';for(let i=0;i<12;i++)ctx.fillRect(i*120-cam*.8,475,55,10);ctx.fillStyle='#173c66';ctx.font='bold 18px Tahoma';ctx.fillText(themes(stage),25,35)}
function draw(){background();for(const o of obstacles){let x=o.x-cam;ctx.fillStyle='#e33131';ctx.fillRect(x,o.y,o.w,o.h);ctx.fillStyle='#851313';ctx.fillRect(x+6,o.y+6,o.w-12,o.h-12)}for(const o of overheads){let x=o.x-cam;ctx.fillStyle='#f08a24';ctx.fillRect(x,o.y,o.w,o.h);ctx.fillStyle='#ffe082';ctx.fillRect(x-8,o.y,o.w+16,10)}let x=player.x-cam,y=player.y;ctx.save();ctx.shadowColor='rgba(0,0,0,.5)';ctx.shadowBlur=8;ctx.fillStyle='#111';ctx.beginPath();ctx.ellipse(x+24,ground+4,28,7,0,0,7);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#f2b183';ctx.beginPath();ctx.arc(x+24,y+17,17,0,7);ctx.fill();ctx.fillStyle='#171717';ctx.beginPath();ctx.arc(x+24,y+10,18,3.2,6.2);ctx.fill();ctx.fillStyle='#159a83';ctx.fillRect(x+5,y+35,38,27);ctx.fillStyle='#f2b183';ctx.fillRect(x-4,y+38,10,20);ctx.fillRect(x+42,y+38,10,20);let leg=Math.sin(player.run)*5;ctx.fillStyle='#254a93';ctx.fillRect(x+8+leg,y+61,12,15);ctx.fillRect(x+27-leg,y+61,12,15);ctx.fillStyle='#111';ctx.fillRect(x+3+leg,y+74,18,5);ctx.fillRect(x+25-leg,y+74,18,5);ctx.fillStyle='#fff';ctx.font='bold 15px Tahoma';ctx.textAlign='center';ctx.fillText('عمر',x+24,y-10);ctx.restore();ctx.textAlign='start';ctx.fillStyle='rgba(0,0,0,.65)';ctx.fillRect(20,395,270,25);ctx.fillStyle='#fff';ctx.font='bold 14px Tahoma';ctx.fillText(`المرحلة ${stage} — عمر — دبل نط`,32,413)}
function loop(t){let dt=Math.min((t-last)/1000||0,.035);last=t;if(running)update(dt);if(messageTimer>0&&(messageTimer-=dt)<=0)msg.classList.remove('visible');draw();requestAnimationFrame(loop)}reset();say('اضغط ابدأ',1);requestAnimationFrame(loop);
